### ISSUE TITLE
 SSLError(1, '[SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:1002)') 

### ISSUE THREAD

**Issue by goldyfruit** [JarbasHiveMind/hivemind_websocket_client#16]
https://github.com/JarbasHiveMind/hivemind_websocket_client/blob/dev/hivemind_bus_client/client.py#L133 should be set to `1_2` or at least `1_1`.

**Comment by JarbasAl** [comment]
you really shouldn't allow self signed certifcates to start with, the code you linked is explicitly downgrading security, browsers etc wont accept it

but if we can increase TLS version there i'm all for it, just keep in mind using self-signed certs is insecure and gives no real protection, treat the connection like it's http and enable hivemind's own crypto. self signed certs will only stop the most basic sniffers in your network and can easily be MITMed

**Comment by JarbasAl** [comment]
SSL support is mainly meant for hosted hivemind instances with a real domain

**Comment by goldyfruit** [comment]
I think having self-signed certificates is better than nothing, maybe just adding a note to the readme mentioning that it's not the best option.
